### PR TITLE
Enh: Add Cookie Policy page

### LINKED ISSUE #21: Separate Cookies Policy text
Currently, in many jurisdictions, a Cookies policy is advisable or required, and when Users view the Cookies notification button for a website, there is the possibility of putting a link to the Cookies policy. At the moment the legal module does not provide a tab for that policy, and an admin would have to put it in the privacy policy. Our privacy policy is already quite long,  it would be a better UI and easier to to read to have the option of a separate Cookies Policy text in the module.

### PR DESCRIPTION
**Pull request by ArchBlood**
Please review and see if this is something that should be added versus what shouldn't be added

fixes #21

### Notes
I'd like to add once more for a note about mobile view vs desktop view seen here https://github.com/humhub-contrib/legal/issues/21#issuecomment-882117064

### CODE REVIEW

**Comment by ArchBlood** [comment]
@luke- here's the rundown of the implementation of the Cookie Policy, it works just like other pages and is then added to the footer along with the other enabled options, personally, I'd rather implement it in a way where it only displays in a specific place but for now, this should do exactly what it's needed. 🤔

**Comment by ArchBlood** [comment]
A thought, instead of adding it to the footer section, maybe only display this on the Cookie notice?

**Comment by luke-** [comment]
I would prefer to add such additional footer pages via the Custom Pages module instead of covering such cases via the Legal Pages module.

**Comment by ArchBlood** [comment]
> I would prefer to add such additional footer pages via the Custom Pages module instead of covering such cases via the Legal Pages module.
> 
> 

Hmm, in that case, would it be possible to implement such a thing into the footer though the custom pages module, currently I'm not seeing an option for this as of yet.

Overall the idea of placing a clickable link in the notice itself should still suffice. :thinking:

**Comment by luke-** [comment]
This option:
image

**Comment by ArchBlood** [comment]
> This option:
> image
> 

In this case, would it be possible to update the footer menu where it's implemented in a way similar to how Facebook has theirs? This could fix some of the UI downsides to adding multiple options to the footer.

**Comment by luke-** [comment]
What downsides do you mean? If there are things to improve about the footer menu, we can create an issue.

**Comment by ArchBlood** [comment]
On mobile view with multiple options in the footer it can become very cluttered and if too many links are placed then the display is very displeasing and looks stretched out.

**Pull request closed without merging**
